<a href="https://colab.research.google.com/github/jayakrishnan004/DSA_Practice/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PYTHON LIBRARIES**

Numpy - Numerical Python.

NumPy array manages homogeneous data.

In [3]:
list1 = [2,3,4,5]
list2 = [6,7,8,9]
new_list = list1+list2
print(type(new_list))
print(f"new_list : {new_list}")

<class 'list'>
new_list : [2, 3, 4, 5, 6, 7, 8, 9]


In [23]:
# importing and checking the library.
import numpy as np  # np is the alias to numpy library.
print(np.__version__)  # __Version__ gives the version of the current library.

num1 = np.array([1,2,3,4])
num2 = np.array([5,6,7,8])
print(type(num1))

# To find the size of the array or the total number of elements.
print(num1.size)

temp = np.array([[2,3,4,5],[6,7,8,9]])
print(temp)
print(f"type : {type(temp)}")
print(f"size : {temp.size}")
print(f"shape : {temp.shape}")  # Shape will return the row and the column.
print(f"Dimension of the array is - {temp.ndim}")

2.1.3
<class 'numpy.ndarray'>
4
[[2 3 4 5]
 [6 7 8 9]]
type : <class 'numpy.ndarray'>
size : 8
shape : (2, 4)
Dimension of the array is - 2


In [25]:
temp2 = np.array([[22,33],[43,53],[63,73]])
print(temp2)

print(f"The type of the array is - {type(temp2)}")
print(f"The size of the array is - {temp.size}")
print(f"The shape of the array is - {temp.shape}")
print(f"Dimension of the array is - {temp2.ndim}")

print(temp2.dtype)




[[22 33]
 [43 53]
 [63 73]]
The type of the array is - <class 'numpy.ndarray'>
The size of the array is - 8
The shape of the array is - (2, 4)
Dimension of the array is - 2
int64


In [32]:

array = np.array([[11,10,9,8],[21,22,20,12],[35,34,33,32],[47,46,45,44]])
print(array)

print(f"The type of the array is - {type(array)}")
print(f"The size of the array is - {array.size}")
print(f"The shape of the array is - {array.shape}")
print(f"Dimension of the array is - {array.ndim}")

print(array.dtype)

# To increase the dimensionality, add one more bracket.
array1 = np.array([[[11,10,9,8],[21,22,20,12],[35,34,33,32],[47,46,45,44]]])
print(f"The shape of the array is - {array1.shape}")

[[11 10  9  8]
 [21 22 20 12]
 [35 34 33 32]
 [47 46 45 44]]
The type of the array is - <class 'numpy.ndarray'>
The size of the array is - 16
The shape of the array is - (4, 4)
Dimension of the array is - 2
int64
The shape of the array is - (1, 4, 4)


In [37]:
value = np.array([[23,34,55],[34,45,66]])
print(value)

print(f"Transpose")
print(value.T)  # To find the transpose.

[[23 34 55]
 [34 45 66]]
Transpose
[[23 34]
 [34 45]
 [55 66]]


In [43]:
# To create an empty array of size 4x4 with int values.
# np.empty((rows,columns),datatype)

empty_array = np.empty((4,3))  # Return a 4x3 matrix with random values of float datatype.
print("Array")
print(empty_array)
new_empty_array = np.empty((4,3),int)  # Return a 4x3 matrix with random values of int datatype.
print("New Array")
print(new_empty_array)



Array
[[3.54643281e-315 0.00000000e+000 6.56938568e-310]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
New Array
[[      717805992               0 132965846458688]
 [              0               0               0]
 [              0               0               0]
 [              0               0               0]]


In [53]:
# ones and zeros

sample = np.ones((3,4),int)
print("1-matrix")
print(sample)

sample1 = np.zeros((3,4),int)
print("0-matrix")
print(sample1)

sample2 = np.eye(4,4)
print("matrix")
print(sample2)

1-matrix
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
0-matrix
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [54]:
a = np.arange(1,21)
print(a)
new_a = a.reshape(4,5)
print(new_a)
print(new_a.flatten)  # Convert the matrix - to single dimensionality.


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
<built-in method flatten of numpy.ndarray object at 0x78ee9747cf30>


In [71]:
b = np.arange(31,101,3)
print(b)
new_b = b.reshape(4,6)
print(new_b)


#---------------METHODS-----------------#

print(f"\n Sum of all elements : {np.sum(b)}")
print(f"\n Mean : {np.mean(b)}")
print(f"\n Maximum value : {np.max(b)}")
print(f"\nMinimum value : {np.min(b)}")
print(f"\n Index of Maximum value : {np.argmax(b)}")
print(f"\n Median : {np.median(b)}")
print(f"\n Standard Deviation : {np.std(b)}")

[ 31  34  37  40  43  46  49  52  55  58  61  64  67  70  73  76  79  82
  85  88  91  94  97 100]
[[ 31  34  37  40  43  46]
 [ 49  52  55  58  61  64]
 [ 67  70  73  76  79  82]
 [ 85  88  91  94  97 100]]

 Sum of all elements : 1572

 Mean : 65.5

 Maximum value : 100

Minimum value : 31

 Index of Maximum value : 23

 Median : 65.5

 Standard Deviation : 20.766559657295186


In [73]:
mat1 = np.array([[44,55],[66,77]])
mat2 = np.array([[10,66],[5,90]])
print("\n ADDITION")
Addition = np.add(mat1,mat2)
print(Addition)

print("\n SUBTRACION")
Subtraction = np.subtract(mat1,mat2)
print(Subtraction)
print(f"\n Absolute value")
print(np.abs(Subtraction))

print("\n MULTIPLICATION")
print(np.multiply(mat1,mat2))

print("\n DIVISION")
print(np.divide(mat1,mat2))


print("\n Sum of row wise elements")
print(np.sum(mat1, axis=1))  # Row Wise Sum - axis = 1.

print("\n Sum of Column wise elements")
print(np.sum(mat1, axis=0))  # Column Wise Sum - axis = 0.


 ADDITION
[[ 54 121]
 [ 71 167]]

 SUBTRACION
[[ 34 -11]
 [ 61 -13]]

 Absolute value
[[34 11]
 [61 13]]

 MULTIPLICATION
[[ 440 3630]
 [ 330 6930]]

 DIVISION
[[ 4.4         0.83333333]
 [13.2         0.85555556]]

 Sum of row wise elements
[ 99 143]

 Sum of Column wise elements
[110 132]
